# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshowapp', '0003_auto_20191015_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
