# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_travel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
