# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-18 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_auto_20191018_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='traveler',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
